### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nwhite89** [levexis/grunt-selenium-webdriver#20]
Is it possible to get a release with the most up-to-date selenium jar since the PR merge #19  ?

**Comment by brunowego** [comment]
+1

**Comment by levexis** [comment]
Sorry, I'm not using selenium myself at the moment. I seem to recall we added it as an option and it will download the version specified if not available. So try that but otherwise please submit a PR with the version you need and I'll run the CI test. Part of the point of this is to have versions that "play nicely" together.... Thanks, Paul

**Comment by levexis** [comment]
Sure will do it now, sorry been away for a while!
