### ISSUE TITLE
Upgrade to selenium 2.47.1

### ISSUE THREAD

**Issue by ascripcaru** [levexis/grunt-selenium-webdriver#23]

**Comment by levexis** [comment]
I've merged in your pull request but tests are failing. One thing I fixed was a change to seleniums output but in my tests the driver is just hanging which makes me suspect that selenium interface may have changed and it is not talking to phantom properly. I've not done much with this recently so if you want to take a look at the tests / validate that the head version is working then would be much appreciated. Otherwise I'll probably be able to take a proper look next week. Will not published npm until tests have passed, can use grunt mocha to run specific tests that hang

**Comment by ascripcaru** [comment]
I found the problem.tomorrow i will raise a pull request

**Comment by ascripcaru** [comment]
@levexis I saw that you already fixed the problem.I am closing the issue
